export const AllTypesProps: Record<string,any> = {
	PubMutation:{
		submitOrder:{
			order:{
				type:"SubmitOrder",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		addBeer:{
			beer:{
				type:"AddBeer",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		editBeer:{
			editBeer:{
				type:"EditBeer",
				array:false,
				arrayRequired:false,
				required:true
			},
			SKUInput:{
				type:"SKUInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		removeBeer:{
			SKUInput:{
				type:"SKUInput",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		cancelOrder:{
			orderDetail:{
				type:"OrderDetail",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	AddBeer:{
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		SKU:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		price:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	EditBeer:{
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		price:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	SKUInput:{
		SKU:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	SubmitOrder:{
		productInOrder:{
			type:"ProductInOrder",
			array:true,
			arrayRequired:true,
			required:true
		}
	},
	ProductInOrder:{
		SKU:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		quantity:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	OrderDetail:{
		number:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:true
		}
	}
}

export const ReturnTypes: Record<string,any> = {
	Beer:{
		name:"String",
		SKU:"String",
		price:"Int"
	},
	ClientQuery:{
		beers:"Beer"
	},
	Query:{
		clientQuery:"ClientQuery",
		pubQuery:"PubQuery"
	},
	Order:{
		number:"Int",
		createdAt:"String",
		orderedBeers:"OrderedBeer"
	},
	OrderedBeer:{
		quantity:"Int",
		beer:"Beer"
	},
	PubQuery:{
		orders:"Order"
	},
	PubMutation:{
		submitOrder:"Boolean",
		addBeer:"Boolean",
		editBeer:"Boolean",
		removeBeer:"Boolean",
		cancelOrder:"Boolean"
	},
	Mutation:{
		pubMutation:"PubMutation"
	}
}